---
- name: create user
  hosts: all
  vars:
   ssh_key_filename: id_rsa
  vars_prompt:
    - name: user
      prompt: "Enter the username"
      private: no
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"
  tasks:
  - name: create user {{user}}
    user:
     name: "{{user}}"
     groups: administrator, root
     append: true
     create_home: true
  - name: generate SSH key "{{ssh_key_filename}}"
    user:
        name: "{{user}}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ssh_key_filename}}
        ssh_key_passphrase: "{{ssh_passphrase}}"
        force: no
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/ansible/auth_key
      dest: /home/{{user}}/.ssh/authorized_key
      owner: "{{user}}"
      group: "{{user}}"
      mode: '0600'
